/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerLogin;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Zero-Inside
 */
public class GuestDashboard extends javax.swing.JFrame {

    /**
     * Creates new form GuestDashboard
     */
    public GuestDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1_Register = new javax.swing.JButton();
        jButton2_Login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zero Airline Reservation System");
        setMinimumSize(new java.awt.Dimension(546, 346));
        setSize(new java.awt.Dimension(546, 346));
        getContentPane().setLayout(null);

        jLabel2.setText("Pesan penerbanganmu sekarang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 20, 170, 20);

        jButton1_Register.setText("Register");
        getContentPane().add(jButton1_Register);
        jButton1_Register.setBounds(300, 20, 73, 23);

        jButton2_Login.setText("Login");
        getContentPane().add(jButton2_Login);
        jButton2_Login.setBounds(400, 20, 57, 23);

        jLabel3.setText("Click Register untuk mendaftar ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 320, 220, 14);

        jLabel4.setText("Click login untuk memesan penerbangan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 320, 220, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/backPBO.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 365));
        jLabel1.setMinimumSize(new java.awt.Dimension(600, 365));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // setter getter

    public JButton getjButton1_Register() {
        return jButton1_Register;
    }

    public void setjButton1_Register(JButton jButton1_Register) {
        this.jButton1_Register = jButton1_Register;
    }

    public JButton getjButton2_Login() {
        return jButton2_Login;
    }

    public void setjButton2_Login(JButton jButton2_Login) {
        this.jButton2_Login = jButton2_Login;
    }
    
    // add action listener
    public void addActionListener(ActionListener al){
        jButton1_Register.addActionListener(al);
        jButton2_Login.addActionListener(al);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Register;
    private javax.swing.JButton jButton2_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(ControllerLogin aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
